services:
  client:
    build:
      dockerfile: Dockerfile
    image: ${LOOPSBENCH_TASK_DOCKER_CLIENT_IMAGE_NAME}
    container_name: ${LOOPSBENCH_TASK_DOCKER_CLIENT_CONTAINER_NAME}
    cap_add:
    - NET_ADMIN
    command:
    - sh
    - -c
    - sleep infinity
    environment:
    - TEST_DIR=${LOOPSBENCH_TEST_DIR}
    volumes:
    - ${LOOPSBENCH_TASK_LOGS_PATH}:${LOOPSBENCH_CONTAINER_LOGS_PATH}
    - ${LOOPSBENCH_TASK_AGENT_LOGS_PATH}:${LOOPSBENCH_CONTAINER_AGENT_LOGS_PATH}
    - loopsbench_shared:/var/lib/loopsbench/.mirror
  tester:
    image: ${LOOPSBENCH_TASK_DOCKER_CLIENT_IMAGE_NAME}
    container_name: ${LOOPSBENCH_TASK_DOCKER_TESTER_CONTAINER_NAME}
    cap_add:
    - NET_ADMIN
    command:
    - sh
    - -c
    - sleep infinity
    depends_on:
    - client
    volumes:
    - loopsbench_shared:/shared
volumes:
  loopsbench_shared: {}
